# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruleengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureurls',
            name='featureurlfields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featureurls', to='ruleengine.FeatureFields'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='featureurls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ruleengine.FeatureURLs'),
        ),
    ]
