# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruleengine', '0002_auto_20160128_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='scheduler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ruleengine.RuleScheduler'),
        ),
    ]
