# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleengine', '0003_auto_20160128_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureurls',
            name='featureurlfields',
        ),
        migrations.AddField(
            model_name='featureurls',
            name='featureurlfields',
            field=models.ManyToManyField(to='ruleengine.FeatureFields'),
        ),
    ]
