# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruleengine', '0004_auto_20160128_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulescheduler',
            name='rulename',
        ),
    ]
