# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleengine', '0006_auto_20160128_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='featureurls',
        ),
        migrations.AddField(
            model_name='rule',
            name='featureurls',
            field=models.ManyToManyField(related_name='rules', to='ruleengine.FeatureURLs'),
        ),
    ]
