# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 13:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_url_field', models.CharField(max_length=50, verbose_name='feature_url_fields')),
                ('field_index', models.PositiveIntegerField(verbose_name='field_index')),
            ],
            options={
                'db_table': 'featurefields',
            },
        ),
        migrations.CreateModel(
            name='FeatureURLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_url', models.TextField(max_length=5000, verbose_name='feature_url')),
                ('featureurlfields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruleengine.FeatureFields')),
            ],
            options={
                'db_table': 'featureurls',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(max_length=30, verbose_name='rule_type')),
                ('rule_name', models.CharField(max_length=30, unique=True, verbose_name='rule_name')),
                ('area_url', models.TextField(verbose_name='area_url')),
                ('createddate', models.DateTimeField(default=datetime.datetime.now, verbose_name='createddate')),
                ('emailid', models.EmailField(max_length=250, verbose_name='emailid')),
                ('featureurls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruleengine.FeatureURLs')),
            ],
            options={
                'db_table': 'rules',
            },
        ),
        migrations.CreateModel(
            name='RuleScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedulertime', models.DateTimeField(default=datetime.datetime.now, verbose_name='schedulertime')),
                ('schedulertype', models.CharField(max_length=20, verbose_name='schedulertype')),
                ('rulename', models.CharField(max_length=30, verbose_name='rulename')),
            ],
            options={
                'db_table': 'rulescheduler',
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='scheduler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruleengine.RuleScheduler'),
        ),
    ]
